Repository Nixtla/statsforecast, pull requests merged in 2023-11, with the labels that each got.

#695 use numpy style in all docstrings
  nbs/src/adapters.prophet.ipynb
  nbs/src/core/distributed.fugue.ipynb
  nbs/src/core/models.ipynb
  nbs/src/distributed.multiprocess.ipynb
  nbs/src/utils.ipynb
  statsforecast/adapters/prophet.py
  statsforecast/distributed/fugue.py
  statsforecast/distributed/multiprocess.py
  statsforecast/models.py
  statsforecast/utils.py
Labels: documentation

#699 feat: _calculate_sigma() explicitly handles series with 1 data point (n=0)
  nbs/src/utils.ipynb
  statsforecast/utils.py
Labels: fix

#701 add mstl_decomposition function
  nbs/docs/how-to-guides/generating_features.ipynb
  nbs/mint.json
  nbs/src/feature_engineering.ipynb
  statsforecast/_modidx.py
  statsforecast/feature_engineering.py
Labels: feature

#706 fix arima var_coef
  nbs/src/arima.ipynb
  statsforecast/arima.py
Labels: fix

#713 fix predict_insample docstrings
  nbs/src/core/models.ipynb
  statsforecast/models.py
Labels: fix

#714 add exogenous features support to models table
  README.md
  nbs/index.ipynb
Labels: documentation
