Repository Nixtla/statsforecast, pull requests merged in 2023-06, with the labels that each got.

#514 Add release drafter
  .github/release-drafter.yml
Labels: enhancement

#533 Update CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: documentation

#535 Update nbs/docs/contribute/ file
  nbs/docs/contribute/contribute.md
  nbs/docs/contribute/docs.mdx
  nbs/docs/contribute/issue-labels.mdx
  nbs/docs/contribute/issues.mdx
  nbs/docs/contribute/step-by-step.md
  nbs/docs/contribute/techstack.mdx
Labels: documentation

#536 Update nbs/ file
  nbs/assets/Inter-VariableFont.ttf
  nbs/assets/logo.png
  nbs/sidebar.yml
  nbs/styles.css
Labels: documentation

#537 Update nbs/docs/contribute/ file
  nbs/docs/contribute/docs.md
  nbs/docs/contribute/issue-labels.md
  nbs/docs/contribute/issues.md
  nbs/docs/contribute/techstack.md
Labels: documentation

#542 Update nbs/ file
  nbs/_quarto.yml
  nbs/styles.css
Labels: documentation

#543 Update nbs/docs/contribute/ file
  nbs/docs/contribute/step-by-step.md
Labels: documentation

#544 Update nbs/docs/contribute/ file
  nbs/docs/contribute/step-by-step.md
Labels: documentation

#546 Update nbs/
  nbs/styles.css
Labels: documentation

#541 Updating Distributed Documentation
  nbs/docs/how-to-guides/distributed/dask.ipynb
  nbs/docs/how-to-guides/distributed/dask.qmd
  nbs/docs/how-to-guides/distributed/ray.ipynb
  nbs/docs/how-to-guides/distributed/ray.qmd
  nbs/docs/how-to-guides/distributed/spark.ipynb
  nbs/docs/how-to-guides/distributed/spark.qmd
  nbs/src/core/distributed.fugue.ipynb
  statsforecast/distributed/fugue.py
Labels: documentation

#545 [DOCS] AutomaticForecasting
  nbs/docs/how-to-guides/Automatic_Forecasting.ipynb
  nbs/docs/how-to-guides/Getting_Started_with_Auto_Arima_and_ETS.ipynb
Labels: documentation

#547 [FIX] Restructure how-to guides
  nbs/docs/how-to-guides/AmazonStatsForecast.ipynb
  nbs/docs/how-to-guides/AutoArima_vs_Prophet.ipynb
  nbs/docs/how-to-guides/ETS_ray_m5.ipynb
  nbs/docs/how-to-guides/Prophet_spark_m5.ipynb
  nbs/docs/how-to-guides/dask.ipynb
  nbs/docs/how-to-guides/distributed/.notest
  nbs/docs/how-to-guides/experiments/.notest
  nbs/docs/how-to-guides/migrating/.notest
  nbs/docs/how-to-guides/migrating_R.qmd
  nbs/docs/how-to-guides/ray.ipynb
  nbs/docs/how-to-guides/spark.ipynb
Labels: documentation

#548 Update nbs/
  nbs/sidebar.yml
Labels: documentation

#568 [FEAT] Add ConstantModel and ZeroModel
  nbs/src/core/models.ipynb
  statsforecast/_modidx.py
  statsforecast/models.py
Labels: feature
