Repository Nixtla/statsforecast, pull requests merged in 2024-06, with the labels that each got.

#793 config: CI, add python 3.12
  .github/workflows/ci.yaml
  action_files/test_ray.py
  dev/environment.yml
  dev/local_environment.yml
  dev/requirements.txt
  setup.py
Labels: dependencies

#854 remove TqdmExperimentalWarning
  nbs/src/core/core.ipynb
  statsforecast/core.py
Labels: enhancement

#853 mfles model reference and experiment
  experiments/mfles/README.md
  experiments/mfles/generate_summary.py
  experiments/mfles/m4_experiments.py
  experiments/mfles/statsforecast_auto_mfles_benchmark.ipynb
  experiments/mfles/summary.md
  nbs/docs/models/MFLES.ipynb
  nbs/imgs/mfles_diagram.png
  nbs/mint.json
Labels: documentation

#861 support multiple seasonalities in mstl_decomposition
  dev/environment.yml
  dev/local_environment.yml
  nbs/src/core/models.ipynb
  nbs/src/feature_engineering.ipynb
  statsforecast/_modidx.py
  statsforecast/feature_engineering.py
  statsforecast/models.py
Labels: fix
