Repository Nixtla/statsforecast, pull requests merged in 2024-09, with the labels that each got.

#895 feat: migrate arima to c++
  .gitignore
  experiments/m3/src/evaluation.py
  nbs/src/arima.ipynb
  python/statsforecast/_modidx.py
  python/statsforecast/arima.py
  setup.py
  src/arima.cpp
  src/statsforecast.cpp
Labels: feature

#899 fix: pass constant in autoarima stepwise
  nbs/src/arima.ipynb
  python/statsforecast/arima.py
Labels: fix

#901 fix: reduce overhead in parallel forecast
  nbs/src/core/core.ipynb
  python/statsforecast/_modidx.py
  python/statsforecast/core.py
Labels: fix

#865 enh: keep target dtype in output
  nbs/src/core/core.ipynb
  nbs/src/core/models.ipynb
  nbs/src/utils.ipynb
  python/statsforecast/core.py
  python/statsforecast/models.py
  python/statsforecast/utils.py
Labels: enhancement

#906 fix: bump build to include submodules in sdist
  python/statsforecast/__init__.py
  settings.ini
Labels: fix

#910 fix: static requirements
  setup.py
Labels: fix

#914 fix: set lower bound on threadpoolctl
  settings.ini
Labels: fix

#915 fix: chunk series in parallel forecast
  nbs/src/core/core.ipynb
  python/statsforecast/__init__.py
  python/statsforecast/_modidx.py
  python/statsforecast/core.py
  settings.ini
Labels: fix

#918 breaking: allowmean and allowdrift True by default in AutoARIMA
  .pre-commit-config.yaml
  experiments/m3/src/data.py
  experiments/m3/src/evaluation.py
  experiments/m3/src/experiment.py
  nbs/src/core/models.ipynb
  python/statsforecast/models.py
  settings.ini
Labels: breaking change

#919 deps: bump ray pin
  settings.ini
Labels: dependencies
