Repository Nixtla/statsforecast, pull requests merged in 2024-04, with the labels that each got.

#808 persist distributed fitted values
  nbs/src/core/distributed.fugue.ipynb
  statsforecast/distributed/fugue.py
Labels: enhancement

#788 tbats fixes
  dev/environment.yml
  dev/local_environment.yml
  experiments/tbats/README.md
  experiments/tbats/data.py
  experiments/tbats/environment.yml
  experiments/tbats/evaluation.py
  experiments/tbats/experiment.py
  experiments/tbats/py_tbats.py
  experiments/tbats/r_tbats.R
  experiments/tbats/src/main.py
  experiments/tbats/src/tbats_py.py
  experiments/tbats/src/tbats_r.R
  nbs/src/core/models.ipynb
  nbs/src/tbats.ipynb
  nbs/src/utils.ipynb
  settings.ini
  statsforecast/_modidx.py
  statsforecast/models.py
  statsforecast/tbats.py
  statsforecast/utils.py
Labels: fix

#812 add SklearnModel
  dev/environment.yml
  dev/local_environment.yml
  nbs/docs/how-to-guides/sklearn_models.ipynb
  nbs/mint.json
  nbs/src/core/models.ipynb
  statsforecast/_modidx.py
  statsforecast/models.py
Labels: feature

#815 use single threaded functions in multiprocessing
  nbs/src/core/core.ipynb
  nbs/src/tbats.ipynb
  statsforecast/_modidx.py
  statsforecast/core.py
  statsforecast/tbats.py
Labels: enhancement

#819 return max float instead of Inf in arima_css_op
  nbs/src/arima.ipynb
  statsforecast/arima.py
Labels: fix

#823 fix refit check for models forward
  nbs/src/core/core.ipynb
  statsforecast/core.py
Labels: enhancement

#822 set target_col=None in _parse_X_level
  dev/environment.yml
  dev/local_environment.yml
  nbs/src/core/core.ipynb
  settings.ini
  statsforecast/core.py
Labels: enhancement

#824 fix syntax warnings in refit check
  nbs/src/core/core.ipynb
  statsforecast/core.py
Labels: enhancement

#828 Fix allowdrift and allowmean in non-stepwise AutoARIMA
  .github/workflows/ci.yaml
  nbs/src/arima.ipynb
  statsforecast/arima.py
Labels: fix
