Repository Nixtla/statsforecast, pull requests merged in 2024-01, with the labels that each got.

#739 use future instead of deprecation warnings
  dev/environment.yml
  dev/local_environment.yml
  nbs/src/core/core.ipynb
  nbs/src/utils.ipynb
  settings.ini
  statsforecast/core.py
  statsforecast/utils.py
Labels: enhancement

#741 ensure float dtype in ets
  nbs/src/ets.ipynb
  statsforecast/ets.py
Labels: fix

#742 add phi to AutoETS init signature
  nbs/src/core/models.ipynb
  nbs/src/ets.ipynb
  statsforecast/ets.py
  statsforecast/models.py
Labels: enhancement

#744 fix predict_in_sample for seasonal naive
  action_files/utils.py
  nbs/src/utils.ipynb
  statsforecast/utils.py
Labels: fix

#578 [FEAT] TBATS model
  nbs/src/core/models.ipynb
  nbs/src/tbats.ipynb
  statsforecast/_modidx.py
  statsforecast/models.py
  statsforecast/tbats.py
Labels: feature

#746 remove seasonal component in CES when data has less than two periods
  nbs/src/ces.ipynb
  statsforecast/ces.py
Labels: fix

#752 fix search_arima
  nbs/src/arima.ipynb
  statsforecast/arima.py
Labels: fix

#754 remove njit from simple functions
  nbs/src/core/models.ipynb
  nbs/src/theta.ipynb
  nbs/src/utils.ipynb
  statsforecast/models.py
  statsforecast/theta.py
  statsforecast/utils.py
Labels: enhancement

#764 add predict_in_sample to intermittent models
  README.md
  nbs/index.ipynb
  nbs/src/core/models.ipynb
  statsforecast/models.py
Labels: enhancement

#768 check exogenous features are present when needed
  nbs/src/core/core.ipynb
  nbs/src/core/models.ipynb
  statsforecast/_modidx.py
  statsforecast/core.py
  statsforecast/models.py
Labels: enhancement

#766 MSTL fixes
  .github/workflows/ci.yaml
  nbs/src/arima.ipynb
  nbs/src/core/models.ipynb
  nbs/src/mstl.ipynb
  statsforecast/arima.py
  statsforecast/models.py
  statsforecast/mstl.py
Labels: fix

#770 Address division by zero warnings in arima
  nbs/src/arima.ipynb
  statsforecast/arima.py
Labels: enhancement

#759 AutoTBATS, experiment, and minor issues
  dev/environment.yml
  dev/local_environment.yml
  experiments/tbats/README.md
  experiments/tbats/environment.yml
  experiments/tbats/src/main.py
  experiments/tbats/src/tbats_py.py
  experiments/tbats/src/tbats_r.R
  nbs/src/core/models.ipynb
  nbs/src/feature_engineering.ipynb
  nbs/src/tbats.ipynb
  settings.ini
  statsforecast/_modidx.py
  statsforecast/models.py
  statsforecast/tbats.py
Labels: feature
