Repository Nixtla/statsforecast, pull requests merged in 2024-05, with the labels that each got.

#836 setup pre-commit
  .github/workflows/lint.yaml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  action_files/clean_nbs
  action_files/imports_with_code.py
  nbs/index.ipynb
  pyproject.toml
  settings.ini
  statsforecast/adapters/prophet.py
  statsforecast/ces.py
  statsforecast/ets.py
  statsforecast/garch.py
Labels: dependencies

#842 Fix SyntaxWarning: invalid escape sequence
  nbs/src/core/models.ipynb
  statsforecast/models.py
Labels: documentation

#846 propagate model alias to fallback model in fit
  nbs/src/core/core.ipynb
  statsforecast/core.py
Labels: fix

#849 support progress bar in parallel forecast
  nbs/src/core/core.ipynb
  statsforecast/_modidx.py
  statsforecast/core.py
Labels: enhancement

#850 store time taken by model in forecast method
  nbs/src/core/core.ipynb
  statsforecast/core.py
Labels: enhancement
