Repository Nixtla/statsforecast, pull requests merged in 2025-02, with the labels that each got.

#984 fix(nelder-mead): argsort before early exit
  include/statsforecast/nelder_mead.h
  nbs/src/ets.ipynb
  nbs/src/theta.ipynb
  python/statsforecast/ets.py
  python/statsforecast/theta.py
  src/ets.cpp
  src/theta.cpp
Labels: fix

#978 Typo: Removed `mean` with `fitted` in doc string of `predict_in_sampl…
  nbs/src/core/models.ipynb
  python/statsforecast/models.py
Labels: documentation

#973 enh(SES): improve implementation
  README.md
  nbs/src/core/models.ipynb
  python/statsforecast/_modidx.py
  python/statsforecast/models.py
Labels: enhancement

#990 Added '~' in the code cell to accurately get the anomalies in AnomalyDetection.ipynb
  nbs/docs/tutorials/AnomalyDetection.ipynb
Labels: documentation

#991 FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  nbs/docs/tutorials/ElectricityLoadForecasting.ipynb
Labels: documentation
